### ISSUE TITLE
Extension doesn't work at ChartJs version 3.2.1.

### ISSUE THREAD

**Issue by Squizelland** [haiiaaa/chartjs-gauge#19] opened 2021-05-04 10:46 UTC
I was trying to use the ChartJs version 3.2.1, but suddenly the gauge doesn't appear. But if i use the 2.9.0 version is still good. Has anyone got the same issue here? Thanks before.

**Comment by jbsgh** [comment] 2021-05-26 12:35
Duplicate of #14

ChartJs 3 and ChartJs 2 are not compatible.

**Comment by haiiaaa** [comment] 2021-05-26 20:40
Duplicate of #14

**Closed by haiiaaa** 2021-05-26 20:40 UTC
Labels: duplicate
