### ISSUE TITLE
Set Range

### ISSUE THREAD

**Issue by klienn** [haiiaaa/chartjs-gauge#13] opened 2020-11-29 08:01 UTC
I wanted to start my chart at negative values and I can't find any solution online, how can I achieve this?

**Comment by haiiaaa** [comment] 2020-11-30 07:19
Are you talking about rotation?

**Comment by klienn** [comment] 2020-11-30 07:42
@haiiaaa no, i want the starting value to be negative. Whenever I tried to use a negative value, the pointer goes beyond the starting bar

**Comment by haiiaaa** [comment] 2020-11-30 07:45
How would you represent a negative value in a pie/doughnut chart? 
Try to a negative value in the example editors https://www.chartjs.org/docs/master/charts/doughnut/

**Comment by haiiaaa** [comment] 2021-04-13 17:46
I think know what you mean now, so I will fix this.

**Comment by haiiaaa** [comment] 2021-05-05 20:51
Fixed in version 0.3.0, duplicate of #18

**Closed by haiiaaa** 2021-05-05 20:51 UTC
Labels: duplicate
